const carDetails = [
  {
    id: 1,
    brand: "Hyundai",
    model: "Elantra GTBase",
    year: 2022,
    bodyType: "Hatchback",
    price: 2400,
    condition: "Used",
    mileage: 30,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: [
      "public/images/2019 Hyundai Elantra GTBase.webp",
      "public/images/Elentral-GTBase-0.webp",
      "public/images/Elentral-GTBase-1.webp",
    ],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 2,
    brand: "Infiniti",
    model: "QX60 Luxe",
    year: 2021,
    bodyType: "SUV",
    price: 5000,
    condition: "Used",
    mileage: 50,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.0L",
    color: "White",
    images: [
      "public/images/2026 INFINITI QX60 Luxe.webp",
      "public/images/QX60-0.webp",
      "public/images/QX60-1.webp",
      "public/images/QX60-2.webp",
    ],
    features: [
      "Leather Seats",
      "Keyless Entry",
      "Lane Assist",
      "Touchscreen Display",
    ],
    description:
      "Comfortable and reliable Honda Accord with advanced safety features and smooth ride.",
  },
  {
    id: 3,
    brand: "Hyundai",
    model: "Elantra N Base",
    year: 2022,
    bodyType: "Sedan",
    price: 10000,
    condition: "Used",
    mileage: 30,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: [
      "public/images/Hyundai Elantra N Base.webp",
      "public/images/NBase-0.webp",
      "public/images/NBase-1.webp",
      "public/images/NBase-2.webp",
    ],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 4,
    brand: "Infiniti",
    model: "QX80 Luxe",
    year: 2021,
    bodyType: "SUV",
    price: 14000,
    condition: "Used",
    mileage: 30,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.0L",
    color: "White",
    images: [
      "public/images/QX80-0.webp",
      "public/images/QX80-1.webp",
      "public/images/QX80-2.webp",
    ],
    features: [
      "Leather Seats",
      "Keyless Entry",
      "Lane Assist",
      "Touchscreen Display",
    ],
    description:
      "Comfortable and reliable Honda Accord with advanced safety features and smooth ride.",
  },
  {
    id: 5,
    brand: "Infiniti",
    model: "QX80 SENSORY AWD",
    year: 2021,
    bodyType: "SUV",
    price: 5000,
    condition: "Used",
    mileage: 30,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.0L",
    color: "White",
    images: [
      "public/images/INFINITI QX80 SENSORY AWD.webp",
    ],
    features: [
      "Leather Seats",
      "Keyless Entry",
      "Lane Assist",
      "Touchscreen Display",
    ],
    description:
      "Comfortable and reliable Honda Accord with advanced safety features and smooth ride.",
  },
  {
    id: 6,
    brand: "Infiniti",
    model: "QX80 SPORT",
    year: 2021,
    bodyType: "SUV",
    price: 7000,
    condition: "Used",
    mileage: 30,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.0L",
    color: "White",
    images: [
      "public/images/INFINITI QX80 SPORT.webp",
      "public/images/QX80-white-0.webp",
      "public/images/QX80-white-1.webp",
      "public/images/QX80-white-2.webp",
    ],
    features: [
      "Leather Seats",
      "Keyless Entry",
      "Lane Assist",
      "Touchscreen Display",
    ],
    description:
      "Comfortable and reliable Honda Accord with advanced safety features and smooth ride.",
  },
  {
    id: 7,
    brand: "Infiniti",
    model: "QX30 Luxury",
    year: 2021,
    bodyType: "Sedan",
    price: 8000,
    condition: "Used",
    mileage: 30,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.0L",
    color: "White",
    images: [
      "public/images/Used 2018 INFINITI QX30 Luxury.webp",
      "public/images/QX30-0.webp",
      "public/images/QX30-1.webp",
      "public/images/QX30-2.webp",
    ],
    features: [
      "Leather Seats",
      "Keyless Entry",
      "Lane Assist",
      "Touchscreen Display",
    ],
    description:
      "Comfortable and reliable Honda Accord with advanced safety features and smooth ride.",
  },
  {
    id: 8,
    brand: "Ford",
    model: "Bronco Badlands",
    year: 2022,
    bodyType: "SUV",
    price: 6000,
    condition: "Used",
    mileage: 50,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: [
      "public/images/Ford Bronco Badlands.webp",
      "public/images/ford-bronco-0.webp",
      "public/images/ford-bronco-1.webp",
      "public/images/ford-bronco-2.webp",
    ],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 9,
    brand: "Ford",
    model: "F-150 Lariat",
    year: 2022,
    bodyType: "Pickup",
    price: 7500,
    condition: "Used",
    mileage: 30,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: [
      "public/images/Ford F-150 Lariat.webp",
      "public/images/F-150-XL-0.webp",
      "public/images/F-150-XL-1.webp",
      "public/images/F-150-XL-2.webp",
    ],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 10,
    brand: "Ford",
    model: "F-150 X",
    year: 2022,
    bodyType: "Pickup",
    price: 4000,
    condition: "Used",
    mileage: 30,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: ["public/images/Ford F-150 X.webp"],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 11,
    brand: "Ford",
    model: "F-150 XLT",
    year: 2022,
    bodyType: "Pickup",
    price: 7000,
    condition: "Used",
    mileage: 30,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: [
      "public/images/F-250-0.webp",
      "public/images/F-250-1.webp",
      "public/images/F-250-2.webp",
    ],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 12,
    brand: "Ford",
    model: "Fusion SE",
    year: 2022,
    bodyType: "Sedan",
    price: 6000,
    condition: "Used",
    mileage: 30,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: [
      "public/images/Ford Fusion SE.webp",
      "public/images/Fusion-0.webp",
      "public/images/Fusion-1.webp",
      "public/images/Fusion-2.webp",
    ],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 13,
    brand: "Ford",
    model: "Mustang EcoBoost Premium",
    year: 2022,
    bodyType: "Coupe",
    price: 2400,
    condition: "Used",
    mileage: 30,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: [
      "public/images/Ford Mustang EcoBoost Premium.webp",
    ],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 14,
    brand: "BMW",
    model: "BMW 1 series M Base",
    year: 2022,
    bodyType: "Coupe",
    price: 8000,
    condition: "Used",
    mileage: 20,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: [
      "public/images/BMW 1 series M Base.webp",
      "public/images/BMW M-series-0.webp",
      "public/images/BMW M-series-1.webp",
      "public/images/BMW M-series-2.webp",
      "public/images/BMW M-series-3.webp",
    ],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 15,
    brand: "BMW",
    model: "BMW 5 SERIES 535I GRAN TURISMO",
    year: 2022,
    bodyType: "Hatchback",
    price: 2400,
    condition: "Used",
    mileage: 30,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: [
      "public/images/BMW 535 Gran Turismo 2014 BMW 5 SERIES 535I GRAN TURISMO.webp",
    ],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 16,
    brand: "BMW",
    model: "BMW 300e xDrive",
    year: 2022,
    bodyType: "Coupe",
    price: 1400,
    condition: "Used",
    mileage: 40,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: [
      "public/images/Certified 2023 BMW 330e xDrive.webp",
    ],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 17,
    brand: "BMW",
    model: "BMW 330f xDrive",
    year: 2022,
    bodyType: "Convertible",
    price: 1400,
    condition: "Used",
    mileage: 40,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: [
      "public/images/Certified 2023 BMW 330e xDrive.webp",
    ],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 18,
    brand: "BMW",
    model: "BMW 320e xDrive",
    year: 2022,
    bodyType: "Coupe",
    price: 1400,
    condition: "Used",
    mileage: 40,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: [
      "public/images/Certified 2023 BMW 330e xDrive.webp",
    ],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 19,
    brand: "BMW",
    model: "BMW 350e xDrive",
    year: 2022,
    bodyType: "Cuople",
    price: 1400,
    condition: "Used",
    mileage: 40,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: [
      "public/images/Certified 2023 BMW 330e xDrive.webp",
    ],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 20,
    brand: "Honda",
    model: "HR-V EX",
    bodyType: "Hatchback",
    year: 2022,
    price: 7000,
    condition: "Used",
    mileage: 200,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: [
      "public/images/Honda HR-V EX.webp",
      "public/images/HR-V-0.webp",
      "public/images/HR-V-2.webp",
      "public/images/HR-V-1.webp",
      "public/images/HR-V-3.webp",
    ],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 21,
    brand: "Honda",
    model: "CR-V Hybrid Sport AWD",
    bodyType: "SUV",
    year: 2022,
    price: 9400,
    condition: "Used",
    mileage: 40,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: [
      "public/images/Honda CR-V Hybrid Sport AWD.webp",
      "public/images/CR-V-0.webp",
      "public/images/CR-V-1.webp",
      "public/images/CR-V-2.webp",
    ],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 22,
    brand: "Hyundai",
    model: "Genesis Couple",
    year: 2022,
    bodyType: "Coupe",
    price: 5400,
    condition: "Used",
    mileage: 40,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: ["public/images/Hyundai Genesis Couple.webp"],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 23,
    brand: "Hyundai",
    model: "Genesis 3.8",
    year: 2022,
    bodyType: "Coupe",
    price: 6000,
    condition: "Used",
    mileage: 40,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: ["public/images/Hyundai Genesis 3.8.webp"],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 24,
    brand: "BMW",
    model: "228 Gran Coupe i xDrive",
    bodyType: "Coupe",
    year: 2022,
    price: 8000,
    condition: "Used",
    mileage: 25,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: [
      "public/images/Used 2024 BMW 228 Gran Coupe i xDrive.webp",
    ],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 25,
    brand: "BMW",
    model: "128 128i 2dr Convertible SULEV",
    bodyType: "Convertible",
    year: 2022,
    price: 6500,
    condition: "Used",
    mileage: 15,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: [
      "public/images/Used 2008 BMW 128 128i 2dr Convertible SULEV.webp",
    ],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine, and excellent fuel economy.",
  },
  {
    id: 26,
    brand: "BMW",
    model: "228 Gran Coupe XDrive",
    bodyType: "Coupe",
    year: 2022,
    price: 14000,
    condition: "Used",
    mileage: 40,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.5L",
    color: "Black",
    images: [
      "public/images/New 2026 BMW 228 Gran Coupe XDrive.webp",
    ],
    features: [
      "Air Conditioning",
      "ABS",
      "Bluetooth",
      "Reverse Camera",
      "Cruise Control",
    ],
    description:
      "Well maintained Toyota Camry with clean interior, smooth engine",
  },
  {
    id: 27,
    brand: "Infiniti",
    model: "QX80 Luxe",
    bodyType: "SUV",
    year: 2021,
    price: 14000,
    condition: "Used",
    mileage: 30,
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.0L",
    color: "White",
    images: [
      "public/images/QX80-white-0.webp",
      "public/images/QX80-white-1.webp",
      "public/images/QX80-white-2.webp",
    ],
    features: [
      "Leather Seats",
      "Keyless Entry",
      "Lane Assist",
      "Touchscreen Display",
    ],
    description:
      "Comfortable and reliable Honda Accord with advanced safety features and smooth ride.",
  },
];

export default carDetails;
