const carDetails = [
  {
    id: 1,
    name: "Hyundai",
    model: "2019 Hyundai Elantra GTBase",
    image: "public/images/2019 Hyundai Elantra GTBase.webp",
    price: 2400,
    millage: 30,
  },
  {
    id: 2,
    name: "Infiniti",
    model: "2026 INFINITI QX60 Luxe",
    image: "public/images/2026 INFINITI QX60 Luxe.webp",
    price: 25000,
    millage: 50,
  },
  {
    id: 3,
    name: "hyundai",
    model: "Hyundai Elantra N Base",
    image: "public/images/Hyundai Elantra N Base.webp",
    price: 10000,
    millage: 30,
  },
  {
    id: 4,
    name: "Infiniti",
    model: "INFINITI QX80 Luxe",
    image: "public/images/INFINITI QX80 Luxe.webp",
    price: 14000,
    millage: 30,
  },
  {
    id: 5,
    name: "Infiniti",
    model: "INFINITI QX80 SENSORY AWD",
    image: "public/images/INFINITI QX80 SENSORY AWD.webp",
    price: 5000,
    millage: 30,
  },
  {
    id: 6,
    name: "Infiniti",
    model: "INFINITI QX80 SPORT",
    image: "public/images/INFINITI QX80 SPORT.webp",
    price: 7000,
    millage: 30,
  },
  {
    id: 7,
    name: "Infiniti",
    model: "2018 INFINITI QX30 Luxury",
    image:
      "public/images/Used 2018 INFINITI QX30 Luxury.webp",
    price: 8000,
    millage: 30,
  },

  {
    id: 8,
    name: "Ford",
    model: "Ford Bronco Badlands",
    image: "public/images/Ford Bronco Badlands.webp",
    price: 6000,
    millage: 50,
  },
  {
    id: 9,
    name: "Ford",
    model: "Ford F-150 Lariat",
    image: "public/images/Ford F-150 Lariat.webp",
    price: 7500,
    millage: 30,
  },
  {
    id: 10,
    name: "Ford",
    model: "Ford F-150 X",
    image: "public/images/Ford F-150 X.webp",
    price: 4000,
    millage: 30,
  },
  {
    id: 11,
    name: "Ford",
    model: "Ford F-150 XLT",
    image: "public/images/Ford F-150 XLT.webp",
    price: 7000,
    millage: 30,
  },
  {
    id: 12,
    name: "Ford",
    model: "Ford Fusion SE",
    image: "public/images/Ford Fusion SE.webp",
    price: 6000,
    millage: 30,
  },
  {
    id: 13,
    name: "Ford",
    model: "Ford Mustang EcoBoost Premium",
    image:
      "public/images/Ford Mustang EcoBoost Premium.webp",
    price: 2400,
    millage: 30,
  },
  {
    id: 14,
    name: "BMW",
    model: "BMW 1 series M Base",
    image: "public/images/BMW 1 series M Base.webp",
    price: 8000,
    millage: 20,
  },
  {
    id: 15,
    name: "BMW",
    model:
      "BMW 535 Gran Turismo 2014 BMW 5 SERIES 535I GRAN TURISMO",
    image:
      "public/images/BMW 535 Gran Turismo 2014 BMW 5 SERIES 535I GRAN TURISMO.webp",
    price: 2400,
    millage: 30,
  },
  {
    id: 16,
    name: "BMW",
    model: "Certified 2023 BMW 330e xDrive",
    image:
      "public/images/Certified 2023 BMW 330e xDrive.webp",
    price: 1400,
    millage: 40,
  },
  {
    id: 17,
    name: "BMW",
    model: "Certified 2023 BMW 330e xDrive",
    image:
      "public/images/Certified 2023 BMW 330e xDrive.webp",
    price: 1400,
    millage: 40,
  },
  {
    id: 18,
    name: "BMW",
    model: "Certified 2023 BMW 330e xDrive",
    image:
      "public/images/Certified 2023 BMW 330e xDrive.webp",
    price: 1400,
    millage: 40,
  },
  {
    id: 19,
    name: "BMW",
    model: "Certified 2023 BMW 330e xDrive",
    image:
      "public/images/Certified 2023 BMW 330e xDrive.webp",
    price: 1400,
    millage: 40,
  },
  {
    id: 20,
    name: "Honda",
    model: "Honda HR-V EX",
    image: "public/images/Honda HR-V EX.webp",
    price: 7000,
    millage: 200,
  },
  {
    id: 21,
    name: "Honda",
    model: "Honda CR-V Hybrid Sport AWD",
    image: "public/images/Honda CR-V Hybrid Sport AWD.webp",
    price: 9400,
    millage: 40,
  },
  {
    id: 22,
    name: "Hyundai",
    model: "Hyundai Genesis Couple",
    image: "public/images/Hyundai Genesis Couple.webp",
    price: 5400,
    millage: 40,
  },
  {
    id: 23,
    name: "Hyundai",
    model: "Hyundai Genesis 3.8",
    image: "public/images/Hyundai Genesis 3.8.webp",
    price: 6000,
    millage: 40,
  },
  {
    id: 24,
    name: "BMW",
    model: "2024 BMW 228 Gran Coupe i xDrive",
    image:
      "public/images/Used 2024 BMW 228 Gran Coupe i xDrive.webp",
    price: 8000,
    millage: 25,
  },
  {
    id: 25,
    name: "BMW",
    model: "Used 2008 BMW 128 128i 2dr Convertible SULEV",
    image:
      "public/images/Used 2008 BMW 128 128i 2dr Convertible SULEV.webp",
    price: 6500,
    millage: 15,
  },
  {
    id: 26,
    name: "BMW",
    model: "New 2026 BMW 228 Gran Coupe XDrive",
    image:
      "public/images/New 2026 BMW 228 Gran Coupe XDrive.webp",
    price: 14000,
    millage: 40,
  },
];

export default carDetails;
